services:
  db:
    image: mysql:8.0
    container_name: microservices_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: riwi_db_meta
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes: 
      - db_data:/var/lib/mysql  # Corrected volume syntax
volumes:
  db_data:
